# Generated by Django 5.2.17 on 2026-08-18 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_employee_employeehistory"),
        ("shifting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftRoster",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_rosters",
                        to="accounts.employee",
                    ),
                ),
                (
                    "shift_master",
                    models.ForeignKey(
                        db_column="shift_master_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rosters",
                        to="shifting.shiftmaster",
                    ),
                ),
            ],
            options={
                "db_table": "ShiftRoster",
                "indexes": [
                    models.Index(fields=["shift_master"], name="idx_roster_shift")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "date"), name="uq_roster_employee_date"
                    )
                ],
            },
        ),
    ]
