# Generated by Django 5.2.17 on 2026-08-16 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('bpjs_no', models.CharField(blank=True, max_length=30, null=True)),
                ('npwp_no', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='organization.jobtitle')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='accounts.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('effective_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='accounts.employee')),
                ('new_job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.jobtitle')),
                ('old_job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.jobtitle')),
            ],
            options={
                'db_table': 'EmployeeHistory',
            },
        ),
    ]
