# Generated by Django 5.2.17 on 2026-08-18 11:10

import hris_project.common.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_employeehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='npwp_no',
            field=hris_project.common.encrypted_fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
