# Generated by Django 5.2.17 on 2026-08-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.BigIntegerField()),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Fixed'), ('attendance', 'Attendance')], default='fixed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rate_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SalaryComponent',
            },
        ),
    ]
