# Generated by Django 5.2.17 on 2026-08-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_employeehistory'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptkp_status', models.CharField(choices=[('TK/0', 'TK/0'), ('TK/1', 'TK/1'), ('TK/2', 'TK/2'), ('TK/3', 'TK/3'), ('K/0', 'K/0'), ('K/1', 'K/1'), ('K/2', 'K/2'), ('K/3', 'K/3')], default='TK/0', max_length=4)),
                ('bpjs_wage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('jkk_risk', models.CharField(choices=[('VERY_LOW', 'Sangat Rendah - 0.24%'), ('LOW', 'Rendah - 0.54%'), ('MEDIUM', 'Sedang - 0.89%'), ('HIGH', 'Tinggi - 1.27%'), ('VERY_HIGH', 'Sangat Tinggi - 1.74%')], default='LOW', max_length=20)),
                ('bpjs_ketenagakerjaan_active', models.BooleanField(default=True)),
                ('bpjs_kesehatan_active', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PayrollRun',
                'constraints': [models.UniqueConstraint(fields=('period_month', 'period_year'), name='unique_payroll_period')],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pph21_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bpjs_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pdf_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=30, null=True)),
                ('calculation_detail', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='accounts.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'Payslip',
                'constraints': [models.UniqueConstraint(fields=('payroll_run', 'employee'), name='unique_payslip_payroll_employee')],
            },
        ),
    ]
