# Generated by Django 5.2.17 on 2026-08-18 11:10

import hris_project.common.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollprofile_payrollrun_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollprofile',
            name='bank_account_no',
            field=hris_project.common.encrypted_fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollprofile',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pdf_password',
            field=hris_project.common.encrypted_fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollprofile',
            name='bpjs_wage',
            field=hris_project.common.encrypted_fields.EncryptedDecimalField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='bank_account_no',
            field=hris_project.common.encrypted_fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='bpjs_amount',
            field=hris_project.common.encrypted_fields.EncryptedDecimalField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='gross_salary',
            field=hris_project.common.encrypted_fields.EncryptedDecimalField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_salary',
            field=hris_project.common.encrypted_fields.EncryptedDecimalField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pph21_amount',
            field=hris_project.common.encrypted_fields.EncryptedDecimalField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_deduction',
            field=hris_project.common.encrypted_fields.EncryptedDecimalField(default=0),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='amount',
            field=hris_project.common.encrypted_fields.EncryptedDecimalField(default=0),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='rate_per_day',
            field=hris_project.common.encrypted_fields.EncryptedDecimalField(blank=True, null=True),
        ),
    ]
