# Generated by Django 5.2.17 on 2026-08-19 04:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_npwp_no'),
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_type', models.CharField(choices=[('MANAGER', 'Manager'), ('PEER', 'Peer'), ('SELF', 'Self')], max_length=20)),
                ('period_type', models.CharField(choices=[('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_kpi_appraisals', to='accounts.employee')),
                ('reviewer', models.ForeignKey(db_column='reviewer_id', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_kpi_appraisals', to='accounts.employee')),
            ],
            options={
                'db_table': 'KpiAppraisal',
                'ordering': ['-year', '-quarter', '-submitted_at'],
                'indexes': [models.Index(fields=['employee', 'year', 'period_type'], name='KpiAppraisa_employe_6cd6b4_idx')],
            },
        ),
    ]
