# Generated by Django 5.2.17 on 2026-08-19 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_npwp_no'),
        ('kpi', '0002_kpiappraisal'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('TODO', 'To-Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_tasks', to='accounts.employee')),
                ('goal', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kpi.kpigoal')),
            ],
            options={
                'db_table': 'KpiTask',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['goal', 'status'], name='KpiTask_goal_id_07fe46_idx')],
            },
        ),
    ]
