# Generated by Django 5.2.17 on 2026-08-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_employee_employeehistory"),
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("level", models.IntegerField(default=1)),
                ("decision", models.CharField(default="pending", max_length=20)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        db_column="approver_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="approval_steps",
                        to="accounts.employee",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_column="request_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_steps",
                        to="approvals.approvalrequest",
                    ),
                ),
            ],
            options={
                "db_table": "ApprovalStep",
                "indexes": [
                    models.Index(fields=["request"], name="idx_appstep_request"),
                    models.Index(fields=["approver"], name="idx_appstep_approver"),
                ],
            },
        ),
    ]
