# Generated by Django 5.2.17 on 2026-08-18 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_employee_employeehistory"),
        ("shifting", "0002_shiftroster"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("clock_in_time", models.DateTimeField(blank=True, null=True)),
                ("clock_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "clock_in_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "clock_in_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "clock_in_photo_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(default="present", max_length=20)),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to="accounts.employee",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        blank=True,
                        db_column="roster_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_logs",
                        to="shifting.shiftroster",
                    ),
                ),
            ],
            options={
                "db_table": "AttendanceLog",
                "indexes": [
                    models.Index(fields=["employee"], name="idx_attendance_employee"),
                    models.Index(fields=["roster"], name="idx_attendance_roster"),
                ],
            },
        ),
    ]
