# Generated by Django 5.2.17 on 2026-08-16 18:37

from django.db import migrations

def seed_roles(apps, schema_editor):
    Role = apps.get_model('uam', 'Role')
    roles = ['Super Admin', 'HR Manager', 'Finance', 'Karyawan']
    for role_name in roles:
        Role.objects.get_or_create(name=role_name)

class Migration(migrations.Migration):

    dependencies = [
        ('uam', '0002_alter_permission_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_roles),
    ]
